const strings = {
  navHome: 'HOME',
  navAllProducts: 'All Products',
  navAdmin: 'Admin',
  navProfile: 'Profile',
  navLogout: 'Logout',
  navSignUp: 'Sign Up',
  navLogIn: 'Log In',
  navCart: 'Cart',
  allProducts: 'All Products',
  aboutUs: 'About us',
  contacts: 'Contacts',
  language: 'Language',
  loadingProducts: 'Loading products...',
  noProductsFound: 'No products found',
  addToCart: 'Add to cart',
  addedToCart: 'added to cart!',
  noDescription: 'No description available',
  filter: 'Filter',
  allRods: 'All rods',
  casting: 'Casting',
  fishingFloat: 'Fishing float',
  baitCasting: 'Bait casting',
  angling: 'Angling',
  allReels: 'All reels',
  spinning: 'Spinning',
  allLine: 'All line',
  braided: 'Braided',
  monofilament: 'Monofilament',
  fluorocarbon: 'Fluorocarbon',
  allLures: 'All lures',
  crankbait: 'Crankbait',
  jig: 'Jig',
  spoon: 'Spoon',
  softBait: 'Soft bait',
  allStorage: 'All storage',
  tackleBox: 'Tackle box',
  backpack: 'Backpack',
  allHooks: 'All hooks',
  single: 'Single',
  treble: 'Treble',
  allWeights: 'All weights',
  sinker: 'Sinker',
  splitShot: 'Split shot',
  allNets: 'All nets',
  landing: 'Landing',
  allClothing: 'All clothing',
  gloves: 'Gloves',
  jacket: 'Jacket',
  wadingPants: 'Wading pants',
  pants: 'Pants',
  fishingShoes: 'Fishing shoes',
  cartEmptyTitle: 'Your Cart is Empty',
  cartEmptyText: 'Continue shopping to add items',
  continueShopping: 'Continue Shopping',
  shoppingCart: 'Shopping Cart',
  product: 'Product',
  price: 'Price',
  quantity: 'Quantity',
  total: 'Total',
  action: 'Action',
  remove: 'Remove',
  subtotal: 'Subtotal',
  shipping: 'Shipping',
  free: 'Free',
  proceedToCheckout: 'Proceed to Checkout',
  checkoutTitle: 'Checkout',
  orderSummary: 'Order Summary',
  shippingAddress: 'Shipping Address',
  shippingAddressPlaceholder: 'Street, city, postal code, country',
  receiptEmail: 'Receipt Email',
  country: 'Country',
  firstName: 'Name',
  lastName: 'Surname',
  addressLine: 'Address',
  city: 'City',
  postalCode: 'Postal Code',
  phoneNumber: 'Phone Number',
  requiredFieldsMessage: 'Please fill in all required shipping and contact fields.',
  placeOrder: 'Place Order',
  placingOrder: 'Placing Order...',
  orderCreated: 'Order created successfully',
  orderFailed: 'Failed to create order',
  checkoutRequiresLogin: 'Please log in to complete your order.',
  checkoutEmpty: 'Your cart is empty. Add products before checkout.',
  goToLogin: 'Go to Login',
  backToCart: 'Back to Cart',
  loadingProduct: 'Loading product...',
  productNotFound: 'Product not found',
  shop: 'Shop',
  category: 'Category',
  inStock: 'In Stock',
  outOfStock: 'Out of Stock',
  available: 'available',
  pleaseLoginToCart: 'Please login to add items to cart',
  invalidQuantity: 'Invalid quantity',
  aboutTitle: 'About FishingGear Pro',
  aboutText: 'Welcome to FishingGear Pro, your ultimate destination for premium fishing equipment. We are dedicated to providing fishermen and women with the highest quality gear to make their fishing experience unforgettable.',
  ourMission: 'Our Mission',
  missionText: 'To supply quality fishing products at affordable prices and provide excellent customer service.',
  contactUs: 'Contact Us',
  contactSubtitle: "We'd love to hear from you. Send us a message!",
  name: 'Name',
  email: 'Email',
  message: 'Message',
  sending: 'Sending...',
  sendMessage: 'Send Message',
  thankYouMessage: "Thank you for your message. We'll get back to you soon!",
  sendFailed: 'Failed to send message. Please try again.',
  login: 'Login',
  username: 'Username',
  password: 'Password',
  loggingIn: 'Logging in...',
  loginSuccess: 'Login successful!',
  loginFailed: 'Login failed',
  dontHaveAccount: "Don't have an account?",
  register: 'Register',
  registerTitle: 'Register',
  confirmPassword: 'Confirm Password',
  passwordMustContain: 'Password must contain:',
  atLeast8Characters: 'At least 8 characters',
  atLeast1Uppercase: 'At least 1 uppercase letter (A-Z)',
  atLeast1Special: 'At least 1 special character (@, !, #, $, %, etc.)',
  passwordNoSpaces: 'Password cannot have leading or trailing spaces',
  passwordMismatch: 'Passwords do not match',
  registering: 'Registering...',
  alreadyHaveAccount: 'Already have an account?',
  registrationSuccess: 'Registration successful! Redirecting to login...',
  registrationFailed: 'Registration failed',
  adminAccessRequired: 'Admin access required',
  backToShop: 'Back to shop',
  adminPanel: 'Admin Panel',
  failedLoadAdminData: 'Failed to load admin data',
  nameCategoryPriceRequired: 'Name, category, and price are required',
  productUpdatedSuccessfully: 'Product updated successfully',
  productAddedSuccessfully: 'Product added successfully',
  failedSaveProduct: 'Failed to save product',
  confirmDeleteProduct: 'Delete this product?',
  productDeleted: 'Product deleted',
  failedDeleteProduct: 'Failed to delete product',
  productMarkedSoldOut: 'Product marked as sold out',
  failedUpdateProduct: 'Failed to update product',
  editProduct: 'Edit product',
  addNewProduct: 'Add new product',
  productName: 'Product name',
  stock: 'Stock',
  categoryExisting: 'Category (existing)',
  selectCategory: 'Select category',
  newCategory: 'New category',
  createNewCategory: 'Create new category',
  imageOptional: 'Image (optional)',
  imagePlaceholder: 'image file name or URL',
  invalidImageType: 'Only PNG and JPEG files are allowed',
  failedUploadImage: 'Failed to upload image',
  selectedFile: 'Selected file',
  uploadingImage: 'Uploading image...',
  description: 'Description',
  saving: 'Saving...',
  adding: 'Adding...',
  saveChanges: 'Save Changes',
  addProduct: 'Add Product',
  cancelEdit: 'Cancel Edit',
  manageProducts: 'Manage products',
  status: 'Status',
  soldOut: 'Sold out',
  markSoldOut: 'Mark Sold Out',
  edit: 'Edit',
  delete: 'Delete',
  weatherConsentTitle: 'Allow weather and location?',
  weatherConsentText: 'To show live weather and fishing conditions, we need your location. Your choice is saved in a cookie.',
  allow: 'Allow',
  decline: 'Decline',
  loadingWeatherData: 'Loading weather data...',
  humidity: 'Humidity',
  wind: 'Wind',
  gusts: 'Gusts',
  locationSource: 'Location Source',
  locationSourceGps: 'GPS (precise)',
  locationSourceIp: 'IP (approximate)',
  locationSourceDefault: 'Default fallback',
  locationSourceUnknown: 'Unknown',
  fishingConditions: 'Fishing Conditions',
  overallQuality: 'Overall Quality',
  bestFishToday: 'Best Fish to Catch Today:',
  method: 'Method',
  location: 'Location',
  tip: 'Tip',
  tipExcellent: 'Perfect day to head out! Bring all your gear.',
  tipGood: 'Good conditions for fishing. Recommended time to fish.',
  tipModerate: 'Decent conditions. Early morning or dusk might be better.',
  tipPoor: 'Challenging conditions. Try deep water fishing or catfish.',
  readyToGoFishing: 'Ready to Go Fishing?',
  checkOutGear: 'Check out our premium fishing gear selection',
  shopAllProducts: 'Shop All Products',
  failedFetchWeather: 'Failed to fetch weather',
  excellent: 'Excellent',
  good: 'Good',
  moderate: 'Moderate',
  poor: 'Poor',
  perfect: 'Perfect',
  veryGood: 'Very Good',
  fair: 'Fair',
  challenging: 'Challenging',
  profileTitle: 'My Profile',
  profileSubtitle: 'Account information',
  profileUsername: 'Username',
  profileEmail: 'Email',
  profileRole: 'Role',
  profileRoleAdmin: 'Administrator',
  profileRoleUser: 'User',
  profileLoginRequired: 'Please log in to view your profile.',
  profileGoLogin: 'Go to Login',
  profileNewPassword: 'New password (optional)',
  profileConfirmPassword: 'Confirm new password',
  profilePasswordHint: 'Leave password fields empty to keep your current password.',
  profileSave: 'Save Profile',
  profileSaving: 'Saving...',
  profileUpdateSuccess: 'Profile updated successfully',
  profileUpdateFailed: 'Failed to update profile',
  inStockCount: (count) => `In stock (${count})`
}

export default strings;
